# Generated by Django 5.0.2 on 2026-05-09 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อลูกค้า')),
                ('phone', models.CharField(max_length=20, verbose_name='เบอร์โทร')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ลูกค้า',
                'verbose_name_plural': 'ลูกค้า',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่ออุปกรณ์')),
                ('unit', models.CharField(max_length=20, verbose_name='หน่วย')),
                ('stock', models.IntegerField(default=0, verbose_name='จำนวนคงเหลือ')),
                ('min_stock', models.IntegerField(default=5, verbose_name='สต็อกขั้นต่ำ')),
            ],
            options={
                'verbose_name': 'อุปกรณ์',
                'verbose_name_plural': 'อุปกรณ์',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อบริการ')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='ราคา')),
                ('duration', models.IntegerField(default=30, verbose_name='เวลา (นาที)')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'บริการ',
                'verbose_name_plural': 'บริการ',
            },
        ),
        migrations.CreateModel(
            name='Barber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อช่าง')),
                ('phone', models.CharField(max_length=20, verbose_name='เบอร์โทร')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='barbers/')),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ช่าง',
                'verbose_name_plural': 'ช่าง',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='จำนวนที่ซื้อ')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='ราคาต่อหน่วย')),
                ('purchase_date', models.DateField(verbose_name='วันที่ซื้อ')),
                ('note', models.TextField(blank=True, null=True, verbose_name='หมายเหตุ')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barbershopapp.equipment', verbose_name='อุปกรณ์')),
            ],
            options={
                'verbose_name': 'รายการซื้ออุปกรณ์',
                'verbose_name_plural': 'รายการซื้ออุปกรณ์',
            },
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(verbose_name='วันนัด')),
                ('appointment_time', models.TimeField(verbose_name='เวลานัด')),
                ('status', models.CharField(choices=[('waiting', 'รอคิว'), ('in_progress', 'กำลังให้บริการ'), ('done', 'เสร็จแล้ว'), ('cancelled', 'ยกเลิก')], default='waiting', max_length=20, verbose_name='สถานะ')),
                ('note', models.TextField(blank=True, null=True, verbose_name='หมายเหตุ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barbershopapp.barber', verbose_name='ช่าง')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barbershopapp.customer', verbose_name='ลูกค้า')),
            ],
            options={
                'verbose_name': 'คิว',
                'verbose_name_plural': 'คิว',
            },
        ),
        migrations.CreateModel(
            name='ServiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField(verbose_name='วันที่บริการ')),
                ('is_paid', models.BooleanField(default=False, verbose_name='ชำระเงินแล้ว')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ราคารวม')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barbershopapp.barber', verbose_name='ช่าง')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barbershopapp.customer', verbose_name='ลูกค้า')),
                ('queue', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='barbershopapp.queue', verbose_name='คิว')),
            ],
            options={
                'verbose_name': 'บันทึกการใช้บริการ',
                'verbose_name_plural': 'บันทึกการใช้บริการ',
            },
        ),
        migrations.CreateModel(
            name='ServiceRecordItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='จำนวน')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='ราคา')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='barbershopapp.servicerecord')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barbershopapp.service', verbose_name='บริการ')),
            ],
            options={
                'verbose_name': 'รายการบริการ',
                'verbose_name_plural': 'รายการบริการ',
            },
        ),
    ]
